In [3]:
# Importing Libraires
import torch
import numpy as np

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [6]:
# Tensor Initializing 
data = [[1,2],[3,4]]
x_data = torch.tensor(data=data)

In [8]:
x_data # Tensors are just arrays with special features

tensor([[1, 2],
        [3, 4]])

In [9]:
# Creating Tensors from numpy array 
arr = np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [10]:
x_data = torch.from_numpy(arr)
x_data

tensor([[1, 2],
        [3, 4]])

In [20]:
# Creating the new tensors using old ones - retian shape and dtypes
x_ones = torch.ones_like(x_data) # retains the shape of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype to float

In [21]:
x_rand

tensor([[0.4195, 0.3734],
        [0.4045, 0.0161]])

In [26]:
x_rand = torch.rand([5,2])

In [27]:
x_rand

tensor([[0.0537, 0.9130],
        [0.7334, 0.0183],
        [0.7436, 0.6523],
        [0.6068, 0.6240],
        [0.6976, 0.7283]])

In [29]:
shape = (2,3,)
x_rand = torch.rand(shape)
x_ones = torch.ones(shape)
x_zeroes = torch.zeros(shape)


In [30]:
x_zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
## More Features - Tensor Attributes 
tensor = torch.rand(2,3)
print(tensor)

tensor([[0.6918, 0.7015, 0.5859],
        [0.0858, 0.5451, 0.9391]])


In [35]:
print(tensor.shape)
print(tensor.device)
print(tensor.dtype)

torch.Size([2, 3])
cpu
torch.float32


In [41]:
print(torch.cuda.is_available())

True


In [42]:
tensor =  torch.rand(3,4,device="cuda")

In [43]:
tensor

tensor([[0.2461, 0.3104, 0.2954, 0.3131],
        [0.6547, 0.9226, 0.6049, 0.4450],
        [0.3546, 0.6578, 0.4397, 0.8102]], device='cuda:0')

In [45]:
tensor.device

device(type='cuda', index=0)

In [46]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [48]:
tensor = torch.rand(2,3)
print(tensor.device)
tensor = tensor.to(device=device)
print(tensor)
print(tensor.device)

cpu
tensor([[0.1856, 0.6386, 0.9641],
        [0.9812, 0.2282, 0.7500]], device='cuda:0')
cuda:0


In [49]:
print(torch.cuda.get_device_name())

NVIDIA GeForce RTX 4060 Laptop GPU


In [50]:
print(torch.cuda.get_device_capability())

(8, 9)


In [52]:
# Indexing and Slicing with Tensors 
tensors = torch.ones(4,4,device="cuda")

In [53]:
tensors

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')

In [54]:
tensors[:,:] = -1

In [55]:
tensors

tensor([[-1., -1., -1., -1.],
        [-1., -1., -1., -1.],
        [-1., -1., -1., -1.],
        [-1., -1., -1., -1.]], device='cuda:0')

In [56]:
tensors[:,0] = 12

In [57]:
tensors

tensor([[12., -1., -1., -1.],
        [12., -1., -1., -1.],
        [12., -1., -1., -1.],
        [12., -1., -1., -1.]], device='cuda:0')

In [60]:
tensors[0:1] = 100


In [61]:
tensors

tensor([[100., 100., 100., 100.],
        [ 12.,  -1.,  -1.,  -1.],
        [ 12.,  -1.,  -1.,  -1.],
        [ 12.,  -1.,  -1.,  -1.]], device='cuda:0')

In [62]:
tensors[0:3] = 5
tensors

tensor([[ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [12., -1., -1., -1.]], device='cuda:0')

In [63]:
print(tensors)

tensor([[ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [12., -1., -1., -1.]], device='cuda:0')


In [65]:
print(tensors[0:1])

tensor([[5., 5., 5., 5.]], device='cuda:0')


In [66]:
tensors = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
print(tensors)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [74]:
print(tensors[0:2])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [79]:
print(tensors[0:1][0:5])

tensor([[1, 2, 3]])


In [80]:
t1 = torch.cat([tensors,tensors,tensors])

In [82]:
t1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [85]:
# Multiplication 
# 1. Element wise 

x = torch.rand(2,3)
y = torch.rand(2,3)
print(x*y)
print(x.mul(y))

tensor([[0.1641, 0.0717, 0.0019],
        [0.1421, 0.2137, 0.6830]])
tensor([[0.1641, 0.0717, 0.0019],
        [0.1421, 0.2137, 0.6830]])


In [86]:
## Matrix multiplication

print(x.matmul(y))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [87]:
x = torch.rand(2,3)
y = torch.rand(3,1)
z = x.matmul(y)
z.shape

torch.Size([2, 1])

In [88]:
z

tensor([[0.6810],
        [0.7079]])

In [89]:
## Tensors to Numpy array 
tensors = torch.ones(5,5)
tensors

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [93]:
arr = tensors.numpy()
arr
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [95]:
tensors[:1] = 5

In [96]:
tensors

tensor([[5., 5., 5., 5., 5.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [97]:
arr

array([[5., 5., 5., 5., 5.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [103]:
## Note : Changes in tensors reflect in arrays and vice versa

In [104]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [105]:
arr[:2] = 0

In [106]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [102]:
tensors

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])